{% set name = "ncio" %}
{% set version = "1.0.1" %}
{% set sha256 = "b336a4fe3f14571f1e16cc6f75a7dfe1b1fdb079603ef48a85b4220690338e2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ncio-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.9
    - numpy
    - netcdf4

test:
  imports:
    - ncio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/ncio
  summary: 'Functions to easily copy a netcdf file, replacing and transforming variables and dimensions.'
  dev_url: https://github.com/mcuntz/ncio
  license: MIT
  license_file: LICENSE
  description: |
    ncio is a Python library functions to copy dimensions, variables,
    attributes, etc. from one netcdf file to a netcdf output
    file. Replacements and transformations can be performed on the
    copied entities such as names can be changed or variables can be
    replaced with other data. It is a thin wrapper of the netCDF4
    Python package that adds no new functionality but rather provides
    convenience functions to work easily with netcdf files.
  doc_url: https://mcuntz.github.io/ncio

extra:
  recipe-maintainers:
    - mcuntz
